language: c, python
python:
  - "2.7"
script: bash ./travis.sh
install:
  - "pip install --upgrade pip --user --quiet"
  - "pip install redis --user"
  - "pip install nose --user"
  - "pip install git+https://github.com/andymccurdy/redis-py.git@2.10.3 --user"
  - "pip install git+https://github.com/idning/python-memcached.git#egg=memcache --user"
services:
  - memcached
  - redis
