language: c, python
python:
  - "2.7"
script: bash ./travis.sh
install:
  - "pip install --upgrade pip --user --quiet"
  - "pip install redis"
  - "pip install nose"
  - "pip install git+https://github.com/andymccurdy/redis-py.git@2.10.3"
  - "pip install git+https://github.com/idning/python-memcached.git#egg=memcache"
services:
  - memcached
  - redis
